export default [
      {
        id:1,
        tag:'aa',
        name:'设施',
        icon:'',
          dishs:[
          {
            id:1,
            price:16,
            name:'WIFI',
            sales:34,
            pic:'dish-1.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'空调',
            sales:12,
            pic:'dish-2.jpg',
            count:0
          }
        ]
      },
      {
        id:2,
        tag:'bb',
        name:'早餐',
        icon:'',
         dishs:[
          {
            id:1,
            price:16,
            name:'含免费早餐',
            sales:34,
            pic:'dish-1.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'无早餐',
            sales:12,
            pic:'dish-2.jpg',
            count:0
          }
        ]
      },
      {
        id:3,
        tag:'cc',
        name:'窗口朝向',
        icon:'',
       dishs:[
          {
            id:1,
            price:16,
            name:'向阳',
            sales:34,
            pic:'dish-1.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'不向阳',
            sales:12,
            pic:'dish-2.jpg',
            count:0
          }
        ]
      },
      {
        id:4,
        tag:'dd',
        name:'市中心',
        icon:'',
                dishs:[
          {
            id:1,
            price:16,
            name:'繁华',
            sales:19,
            pic:'dish-7.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'离市中心远',
            sales:12,
            pic:'dish-8.jpg',
            count:0
          }
        ]
      },
      {
        id:5,
        tag:'ee',
        name:'按摩服务',
        icon:'',
        dishs:[
          {
            id:1,
            price:16,
            name:'有服务',
            sales:34,
            pic:'dish-1.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'并没有什么服务',
            sales:12,
            pic:'dish-2.jpg',
            count:0
          }
        ]
      },
      {
        id:6,
        tag:'ff',
        name:'麻将房',
        icon:'',
        dishs:[
          {
            id:1,
            price:16,
            name:'有麻将房',
            sales:34,
            pic:'dish-1.jpg',
            count:0
          },
          {
            id:2,
            price:10,
            name:'没有',
            sales:12,
            pic:'dish-2.jpg',
            count:0
          }
        ]
      }
    ]